# Generated by Django 3.2.12 on 2024-03-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(default='', max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('phone', models.CharField(default='', max_length=15)),
                ('status', models.BooleanField(default='1')),
                ('role', models.CharField(default='crew', max_length=100)),
                ('ship', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(default='', max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('phone', models.CharField(default='', max_length=15)),
                ('status', models.BooleanField(default='1')),
                ('role', models.CharField(default='port', max_length=100)),
            ],
        ),
    ]
