# Generated by Django 3.2.12 on 2024-03-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_crew_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='crew',
            name='added_user',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='port',
            name='added_user',
            field=models.CharField(default='', max_length=50),
        ),
    ]
