# Generated by Django 3.2.12 on 2024-03-02 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_port_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(default='', max_length=50)),
                ('phone', models.CharField(default='', max_length=15)),
                ('source', models.CharField(default='', max_length=150)),
                ('destination', models.CharField(default='', max_length=150)),
                ('status', models.BooleanField(default='1')),
                ('role', models.CharField(default='ship', max_length=100)),
                ('added_user', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
