# Generated by Django 3.2.12 on 2024-03-03 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_remove_ship_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('containerNumber', models.CharField(max_length=100)),
                ('source', models.CharField(default='', max_length=150)),
                ('destination', models.CharField(default='', max_length=150)),
                ('ship', models.CharField(default='', max_length=150)),
                ('source_status', models.BooleanField(default='1')),
                ('destination_status', models.BooleanField(default='1')),
                ('status', models.BooleanField(default='1')),
                ('added_user', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
