# Generated by Django 3.2.12 on 2024-03-03 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_container'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='destination_status',
            field=models.BooleanField(default=''),
        ),
        migrations.AlterField(
            model_name='container',
            name='source_status',
            field=models.BooleanField(default=''),
        ),
    ]
