# Generated by Django 5.0.4 on 2024-04-09 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_ship_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_start_time', models.DateTimeField()),
                ('predicted_end_time', models.DateTimeField()),
                ('predicted_source', models.CharField(max_length=150)),
                ('predicted_destination', models.CharField(max_length=150)),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.ship')),
            ],
        ),
    ]
