# Generated by Django 3.2.12 on 2024-04-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_routeprediction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crew',
            name='ship',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
